server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3307/samp?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  mvc:
    view:
      prefix: /
      suffix: .html


logging:
  file:
    name: log/log.log
  level:
    root: info
    hhf:
      mybatisplusdemo : debug

mybatis-plus:
  type-aliases-package: hhf.mybatisplusdemo.entity
  mapper-locations: classpath:/gsy/mybatisplusdemo/mapper/*.xml







